"""
terminal_engine.py
==================
The Terminal Elegance design system: a reusable, ATS-clean resume engine.

This file is the DESIGN. You should rarely need to edit it.
It knows how to draw the masthead, section headers, bullets, skills,
jobs, education, references, the circuit traces, the footer, and the
end-of-file marker — all as ATS-clean vector graphics with an
extractable text layer and embedded fonts.

To create a resume you do NOT edit this file. Instead you write a small
config (see configs/*.py) that supplies content, and call build().

Design spec (Terminal Elegance):
  - White paper, near-black cold ink, phosphor-green accent in 3 registers
  - JetBrains Mono (machine voice) + Instrument Sans (humanist prose)
  - Masthead styled like a shell prompt; tmux-style contact status bar
  - Section headers as // COMMENTS on hairlines ending in a green node
  - Bullets hang from vector chevrons; dates are mono timestamps [like this]
  - Circuit traces in corners (whitespace only); // end of file marker
  - Two-pass build for accurate page totals; keep-together logic for jobs
"""
from reportlab.lib.pagesizes import letter
from reportlab.lib.colors import HexColor
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# ----- fonts (bundled ./fonts first, Anthropic skills path as fallback) -----
import os as _os
_HERE = _os.path.dirname(_os.path.abspath(__file__))
_ROOT_DIR = _os.path.dirname(_HERE)
_FONT_DIRS = [_os.path.join(_ROOT_DIR, "fonts"),
              _os.path.join(_HERE, "fonts"),
              "/mnt/skills/examples/canvas-design/canvas-fonts"]
FDIR = next((d for d in _FONT_DIRS
             if _os.path.exists(_os.path.join(d, "JetBrainsMono-Regular.ttf"))), _FONT_DIRS[0])
pdfmetrics.registerFont(TTFont("Mono",  f"{FDIR}/JetBrainsMono-Regular.ttf"))
pdfmetrics.registerFont(TTFont("MonoB", f"{FDIR}/JetBrainsMono-Bold.ttf"))
pdfmetrics.registerFont(TTFont("Sans",  f"{FDIR}/InstrumentSans-Regular.ttf"))
pdfmetrics.registerFont(TTFont("SansB", f"{FDIR}/InstrumentSans-Bold.ttf"))
pdfmetrics.registerFont(TTFont("SansI", f"{FDIR}/InstrumentSans-Italic.ttf"))

# ----- palette (the single green voltage, stepped) -----
PAPER       = HexColor('#FFFFFF')
INK         = HexColor('#0B1220')   # near-black, cold cast
BODY_TXT    = HexColor('#222B38')
MUT         = HexColor('#5B6472')   # muted slate
GREEN_DEEP  = HexColor('#047857')   # readable text green
GREEN_VIVID = HexColor('#16C172')   # marks: cursor, chevrons, nodes
MINT_RULE   = HexColor('#BBEAD3')   # hairlines
MINT_TINT   = HexColor('#F0FBF5')   # status-bar fill
CYAN_DOT    = HexColor('#22B8CF')   # single soldering point

# ----- geometry -----
PAGE_W, PAGE_H = letter
ML, MR = 46, 46
MT, MB = 44, 42
CW = PAGE_W - ML - MR
LH = 13.6     # body leading
BODY = 9.0    # body font size


def wrap(c, text, font, size, mw):
    words = text.split(); lines = []; cur = ""
    for w in words:
        t = f"{cur} {w}".strip()
        if c.stringWidth(t, font, size) <= mw:
            cur = t
        else:
            if cur: lines.append(cur)
            cur = w
    if cur: lines.append(cur)
    return lines


class TerminalResume:
    """The Terminal Elegance rendering engine."""
    SECTION_H = 30
    BGAP = 1.1   # air between bullet items

    def __init__(self, path, contact, total=None, role_line="", subject=""):
        self.c = canvas.Canvas(path, pagesize=letter)
        self.contact = contact
        self.role_line = role_line
        self.c.setTitle(f"{contact['name']} - Resume")
        self.c.setAuthor(contact['name'])
        self.c.setSubject(subject)
        self.c.setCreator(contact['name'])
        self.c.setProducer(contact['name'])
        self.page = 1
        self.total = total
        self.y = PAGE_H - MT

    # ---------- low level ----------
    @property
    def remaining(self):
        return self.y - MB

    def _prompt(self):
        p = self.contact.get('prompt')
        if p: return p
        parts = self.contact['name'].lower().split()
        return f"{parts[0]}@{parts[-1]}:~$" if len(parts) > 1 else f"{parts[0]}@resume:~$"

    def _footer(self):
        c = self.c
        c.setStrokeColor(MINT_RULE); c.setLineWidth(0.6); c.line(ML, 33, PAGE_W - MR, 33)
        c.setFont("Mono", 6.3); c.setFillColor(MUT)
        c.drawString(ML, 24.5, self.contact['footer'])
        c.setFillColor(GREEN_DEEP)
        pg = f"{self.page:02d} / {self.total:02d}" if self.total else f"{self.page:02d}"
        c.drawRightString(PAGE_W - MR, 24.5, pg)
        c.setStrokeColor(GREEN_VIVID); c.setLineWidth(0.9)
        c.line(ML, 11.5, ML + 40, 11.5); c.line(ML + 40, 11.5, ML + 50, 16.5)
        c.setFillColor(GREEN_VIVID); c.circle(ML + 52, 17.2, 1.7, stroke=0, fill=1)

    def _cont_header(self):
        c = self.c
        c.setFont("Mono", 6.8); c.setFillColor(MUT); c.drawString(ML, PAGE_H - 30, self._prompt())
        c.setFillColor(INK); c.setFont("MonoB", 6.8)
        c.drawRightString(PAGE_W - MR, PAGE_H - 30, self.contact['cont_header'])
        c.setStrokeColor(MINT_RULE); c.setLineWidth(0.6); c.line(ML, PAGE_H - 36, PAGE_W - MR, PAGE_H - 36)
        self.y = PAGE_H - 52

    def _newpage(self):
        self._footer(); self.c.showPage(); self.page += 1; self._cont_header()

    def _need(self, pts):
        if self.remaining < pts:
            self._newpage()

    def save(self):
        self._footer(); self.c.save()

    # ---------- measuring ----------
    def bullet_h(self, t):
        return len(wrap(self.c, t, "Sans", BODY, CW - 14)) * LH + self.BGAP

    def para_h(self, t, bold=False):
        return len(wrap(self.c, t, "SansB" if bold else "Sans", BODY, CW)) * LH

    # ---------- masthead ----------
    def masthead(self):
        c = self.c; ct = self.contact
        c.setFont("Mono", 7.2); c.setFillColor(MUT); c.drawString(ML, PAGE_H - 52, f"{self._prompt()} whoami")
        # top-right circuit traces (whitespace)
        c.setStrokeColor(GREEN_VIVID); c.setLineWidth(0.9); x2 = PAGE_W - MR
        c.line(x2, PAGE_H - 50, x2 - 64, PAGE_H - 50); c.line(x2 - 64, PAGE_H - 50, x2 - 76, PAGE_H - 58)
        c.setFillColor(GREEN_VIVID); c.circle(x2 - 78, PAGE_H - 59.2, 1.7, stroke=0, fill=1)
        c.setStrokeColor(CYAN_DOT); c.setLineWidth(0.7); c.line(x2, PAGE_H - 44, x2 - 30, PAGE_H - 44)
        c.setFillColor(CYAN_DOT); c.rect(x2 - 34, PAGE_H - 45.5, 3, 3, stroke=0, fill=1)
        # name + cursor block
        name = ct['name'].upper()
        c.setFont("SansB", 30); c.setFillColor(INK); c.drawString(ML, PAGE_H - 84, name)
        nw = c.stringWidth(name, "SansB", 30)
        c.setFillColor(GREEN_VIVID); c.rect(ML + nw + 7, PAGE_H - 84 - 1.5, 10.5, 22, stroke=0, fill=1)
        # role line
        c.setFont("MonoB", 9.5); c.setFillColor(GREEN_VIVID); c.drawString(ML, PAGE_H - 101, ">")
        c.setFillColor(GREEN_DEEP); c.setFont("Mono", 9.5)
        c.drawString(ML + 10, PAGE_H - 101, self.role_line)
        # contact status bar
        contact = ct['bar']
        size = 7.5
        while c.stringWidth(contact, "Mono", size) > CW - 18 and size > 6.2:
            size -= 0.1
        bar_y = PAGE_H - 126
        c.setFillColor(MINT_TINT); c.setStrokeColor(MINT_RULE); c.setLineWidth(0.7)
        c.roundRect(ML, bar_y, CW, 17, 3, stroke=1, fill=1)
        c.setFont("Mono", size); c.setFillColor(GREEN_DEEP); tx = ML + 9; ty = bar_y + 5.4
        c.drawString(tx, ty, contact)
        def seg(s):
            i = contact.find(s)
            if i < 0: return None
            x0 = tx + c.stringWidth(contact[:i], "Mono", size); x1 = x0 + c.stringWidth(s, "Mono", size)
            return (x0, bar_y, x1, bar_y + 17)
        for url, key in ct.get('links', []):
            r = seg(key)
            if r: c.linkURL(url, r, relative=0)
        self.y = bar_y - 18

    # ---------- structure ----------
    def _sh(self, title):
        c = self.c; self.y -= 11
        c.setFont("MonoB", 10); c.setFillColor(GREEN_VIVID); c.drawString(ML, self.y, "//")
        tw = c.stringWidth("// ", "MonoB", 10); c.setFillColor(INK); c.drawString(ML + tw, self.y, title.upper())
        te = ML + tw + c.stringWidth(title.upper(), "MonoB", 10)
        c.setStrokeColor(MINT_RULE); c.setLineWidth(0.7); c.line(te + 9, self.y + 3.2, PAGE_W - MR - 7, self.y + 3.2)
        c.setFillColor(GREEN_VIVID); c.rect(PAGE_W - MR - 4.2, self.y + 1.4, 3.6, 3.6, stroke=0, fill=1)
        self.y -= 15

    def section(self, title, min_after=70):
        if self.remaining < self.SECTION_H + min_after:
            self._newpage()
        self._sh(title)

    def section_block(self, title, draw):
        h = draw(True)
        if self.remaining < self.SECTION_H + h:
            self._newpage()
        self._sh(title); draw(False)

    def para(self, t, bold=False):
        f = "SansB" if bold else "Sans"
        for line in wrap(self.c, t, f, BODY, CW):
            self._need(LH); self.c.setFont(f, BODY); self.c.setFillColor(BODY_TXT)
            self.c.drawString(ML, self.y, line); self.y -= LH

    def bullet(self, t):
        lines = wrap(self.c, t, "Sans", BODY, CW - 14); self._need(len(lines) * LH + self.BGAP)
        c = self.c; c.setFillColor(GREEN_VIVID); p = c.beginPath()
        p.moveTo(ML + 1.5, self.y + 0.8); p.lineTo(ML + 1.5, self.y + 6.2); p.lineTo(ML + 6.0, self.y + 3.5); p.close()
        c.drawPath(p, stroke=0, fill=1); c.setFillColor(BODY_TXT)
        for line in lines:
            c.setFont("Sans", BODY); c.drawString(ML + 14, self.y, line); self.y -= LH
        self.y -= self.BGAP

    def skill(self, cat, items, col=118):
        lines = wrap(self.c, items, "Sans", BODY, CW - col); self._need(len(lines) * LH)
        c = self.c; c.setFont("MonoB", 7.8); c.setFillColor(GREEN_DEEP); c.drawString(ML, self.y, cat)
        c.setFillColor(BODY_TXT)
        for line in lines:
            c.setFont("Sans", BODY); c.drawString(ML + col, self.y, line); self.y -= LH
        self.y -= 2.0

    def job(self, role, company, dates, all_bullets=None):
        head = 16; fb = all_bullets or []
        ch = sum(self.bullet_h(b) for b in fb) or LH * 2
        self._need(head + ch)
        c = self.c; c.setFont("SansB", 10.5); c.setFillColor(INK); c.drawString(ML, self.y, role)
        rw = c.stringWidth(role, "SansB", 10.5); c.setFont("Sans", 10.5); c.setFillColor(MUT)
        c.drawString(ML + rw, self.y, f"  ·  {company}")
        c.setFont("Mono", 8); c.setFillColor(GREEN_DEEP); c.drawRightString(PAGE_W - MR, self.y + 0.5, f"[{dates}]")
        self.y -= head
        for b in fb: self.bullet(b)

    def edu(self, degree, school, dates):
        self._need(LH * 2 + 5); c = self.c; c.setFont("SansB", 9.5); c.setFillColor(INK); c.drawString(ML, self.y, degree)
        if dates:
            c.setFont("Mono", 7.6); c.setFillColor(GREEN_DEEP); c.drawRightString(PAGE_W - MR, self.y + 0.5, f"[{dates}]")
        self.y -= LH; c.setFont("Sans", 9); c.setFillColor(MUT); c.drawString(ML, self.y, school); self.y -= LH + 5

    def speaking_line(self, lead, detail):
        c = self.c; c.setFont("SansB", 9); c.setFillColor(INK); c.drawString(ML, self.y, lead)
        lw = c.stringWidth(lead, "SansB", 9); c.setFont("SansI", 9); c.setFillColor(MUT)
        c.drawString(ML + lw + 5, self.y, detail); self.y -= LH + 2

    def publication(self, title, tag, desc, url):
        c = self.c; c.setFont("SansB", 9.5); c.setFillColor(INK); c.drawString(ML, self.y, title)
        c.setFont("Mono", 7.6); c.setFillColor(GREEN_DEEP); c.drawRightString(PAGE_W - MR, self.y + 0.5, f"[{tag}]")
        self.y -= LH; c.setFont("Sans", 9); c.setFillColor(MUT); c.drawString(ML, self.y, desc); self.y -= LH
        c.setFont("Mono", 7.6); c.setFillColor(GREEN_DEEP); c.drawString(ML, self.y, url)
        uw = c.stringWidth(url, "Mono", 7.6)
        c.linkURL("https://" + url, (ML, self.y - 2, ML + uw, self.y + 8), relative=0); self.y -= LH + 4

    def refs_two_col(self, left, right):
        rows = max(len(left), len(right)); self._need(rows * (LH * 3 + 4)); c = self.c; rx = ML + CW / 2 + 8; sy = self.y
        def col(refs, x):
            self.y = sy
            for n, role, ct_, cv, lb in refs:
                c.setFont("SansB", 9.5); c.setFillColor(INK); c.drawString(x, self.y, n)
                nw = c.stringWidth(n, "SansB", 9.5); c.setFont("Mono", 7.2); c.setFillColor(GREEN_DEEP)
                c.drawString(x + nw + 5, self.y + 0.5, f"[{lb.lower()}]"); self.y -= LH
                c.setFont("Sans", 8.6); c.setFillColor(MUT); c.drawString(x, self.y, role); self.y -= LH - 2
                c.setFont("Mono", 7.6); c.setFillColor(BODY_TXT); c.drawString(x, self.y, f"{ct_.lower()}: {cv}"); self.y -= LH + 4
            return self.y
        e1 = col(left, ML); e2 = col(right, rx); self.y = min(e1, e2)

    def endfile(self):
        self._need(20); c = self.c; self.y -= 6
        c.setStrokeColor(MINT_RULE); c.setLineWidth(0.6); c.line(ML, self.y + 3, PAGE_W - MR, self.y + 3)
        c.setFont("Mono", 6.8); c.setFillColor(MUT); msg = "// end of file"
        c.drawCentredString(PAGE_W / 2, self.y - 7, msg)
        mw = c.stringWidth(msg, "Mono", 6.8); c.setFillColor(GREEN_VIVID); c.rect(PAGE_W / 2 + mw / 2 + 3, self.y - 8.5, 4.5, 7, stroke=0, fill=1)
        self.y -= 16

    def gap(self, p=10):
        self.y -= p


def build(path, render_fn, contact, role_line, subject):
    """Two-pass build: count pages, then render with totals.

    render_fn(resume) is a function that draws the body using the
    resume object's methods. It is called twice (once to count pages,
    once for real), so it must be deterministic.
    """
    import tempfile, os
    tmp = tempfile.mktemp(suffix='.pdf')
    r0 = TerminalResume(tmp, contact, total=None, role_line=role_line, subject=subject)
    render_fn(r0); n = r0.page; r0.save()
    try: os.remove(tmp)
    except OSError: pass
    r = TerminalResume(path, contact, total=n, role_line=role_line, subject=subject)
    render_fn(r); r.save()
    return n
